eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:      
  datasource:
   url: jdbc:mysql://47.107.34.159:3306/Blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
   username: root
   password: sdad23307216
   driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.107.34.159
    port: 6379  
mybatis:
  mapper-locations: classpath:mapper/*.xml      
  type-aliases-package: Pojo
env:
  env
  
  
  
